name: Publish amd64 and arm64 container image to registry
on:
  push:
    branches:
      - "main"

  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  REPO_IMAGE: mohamed-rafraf/tink-container-runtime

jobs:
  push_to_registry:
    name: Push image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Container metadata setup
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_IMAGE }}
          tags: |
            type=semver,pattern={{raw}}
            type=raw,value=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Buildx (build)
        working-directory: container-runtime/
        run: |
          docker buildx build --output "type=image,push=true" ${{ steps.meta.outputs.buildx_args }} .